### ISSUE TITLE
error when model trained on one class

### ISSUE THREAD

**Issue by minooei** [Chien-Hung/DetVisGUI#1]
Hi
thank you for this great tool.
I want to share an error that I encountered when I was trying to see the results for a dataset with only one class.
when I debug the code I noticed that the variable "cls_objs" in line 460 was a list instead of an array 
https://github.com/Chien-Hung/DetVisGUI/blob/5741f965c80e74ba4572e67ce99aac759832c062/DetVisGUI.py#L460
so I had to write this cls_objs = cls_objs[0]
I think the problem, is in the get_det_results function because it returned an array of list ie: [[list([array([[,,,
https://github.com/Chien-Hung/DetVisGUI/blob/5741f965c80e74ba4572e67ce99aac759832c062/DetVisGUI.py#L155
finally, after some changes, it worked fine. this situation only happened when I trained on a dataset with one class.

**Comment by Chien-Hung** [comment]
Hello, I trained a model on one class by mmdetection to check, but I didn't find the problem. 
Which detection framework (or code) do you use?
The '.pkl' file seems to be a temporary file, and doesn't have a formal format. 
I add the result format figure, DetVisGUI uses in the README.md, hoping it would be useful.

**Comment by minooei** [comment]
Thanks a lot, so there might be a problem with my setup or custom dataset.
I'm closing the issue.
Best.
