### ISSUE TITLE
support json input for det_file

### ISSUE THREAD

**Issue by minooei** [Chien-Hung/DetVisGUI#3]
I'm trying to visualize some detector's output but I have only the standard coco json output of the detector, not the pkl file.
I think we can add support for that in the get_det_results method?

**Comment by Chien-Hung** [comment]
OK, I will try to support this in these day.

**Comment by Chien-Hung** [comment]
Hi, I make DetVisGUI support coco json output format for det_file. 
You can test it. If there are no problem, I would close this issue.

**Comment by minouei-kl** [comment]
Awesome!
I test it and it is working as intended.
thanks again.
