### ISSUE TITLE
Run on a specific GPU

### ISSUE THREAD

**Issue by EdyQiu** [Chien-Hung/DetVisGUI#4]
Thanks for the GUI, it is really amazing!
Would you mind give me some suggestions on running the GUI on a specific GPU(in my case, card 2)?
I did some tests and it seems that 4 GPU cards are required by default, though only the first and the last ones are used (e.g. card 0 and card 3).
I changed the mmdetection/mmdet/apis/inference.py by adding the third line.
###########
if checkpoint is not None:
        map_loc = 'cpu' if device == 'cpu' else None
        map_loc = 'cuda:0'
###########
and add "os.environ['CUDA_VISIBLE_DEVICES']= '2,3'" in the DetVisGUI_test file.
It works and starts to run on card 2 only.

I just wonder that is that possible to change DetVisGUI_test file only.
Just in case that my change in "inference.py" will affect other things. 

Many thanks!

**Comment by Chien-Hung** [comment]
Hi, you can try to add ' --device cuda:2 '  in the command :

python DetVisGUI_test.py configs/faster_rcnn_r50_fpn_1x_coco.py ./faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth data/test_images --device cuda:2

**Comment by EdyQiu** [comment]
> Hi, you can try to add ' --device cuda:2 ' in the command :
> 
> python DetVisGUI_test.py configs/faster_rcnn_r50_fpn_1x_coco.py ./faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth data/test_images --device cuda:2

![image](https://user-images.githubusercontent.com/23387293/103732343-23859800-5022-11eb-8eb4-8e039e479d77.png)
![image](https://user-images.githubusercontent.com/23387293/103732387-3304e100-5022-11eb-8a49-171ea27fc0cd.png)
Thanks for your reply! I initially thought there are only two choices, cpu and cuda, haha.
I tried to set the device to be cuda:2 and cuda:3 respectively. 
In the first case, both card 2 and 3 are used, and in the second case, only card 3 is used.
Though my requirement is totally satisfied(I can use both cards), I just want to share these results ~
